### ISSUE TITLE
ModuleNotFoundError: No module named 'colour.utilities'; 'colour' is not a package

### ISSUE THREAD

**Issue by SteveKing** [crowsonkb/iterm_schemer#1]
I installed python3 from Homebrew, then installed scipy and numpy via pip3.  On my first run of your script I got `ModuleNotFoundError: No module named 'colour'`, so I installed colour via pip3.  On the second run I got the error in the subject line.

It sounds like a really interesting script. I prefer dark backgrounds so I won't actually be able to make use of it, but I love the idea and wanted to see how the automatic color conversions worked out.

```
macabre:~/tmp/iterm_schemer$ python3 -m iterm_schemer InputDark.itermcolors OutputLight.itermcolors --src-bg dark --dst-bg light --invert
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sking/tmp/iterm_schemer/iterm_schemer/__main__.py", line 8, in <module>
    from iterm_schemer.cam02ucs import get_conds, rgb_to_ucs, translate
  File "/Users/sking/tmp/iterm_schemer/iterm_schemer/cam02ucs.py", line 6, in <module>
    import colour
ModuleNotFoundError: No module named 'colour'

macabre:~/tmp/iterm_schemer$ pip3 install colour
Collecting colour
  Downloading colour-0.1.4-py2.py3-none-any.whl
Installing collected packages: colour
Successfully installed colour-0.1.4

macabre:~/tmp/iterm_schemer$ python3 -m iterm_schemer InputDark.itermcolors OutputLight.itermcolors --src-bg dark --dst-bg light --invert
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/sking/tmp/iterm_schemer/iterm_schemer/__main__.py", line 8, in <module>
    from iterm_schemer.cam02ucs import get_conds, rgb_to_ucs, translate
  File "/Users/sking/tmp/iterm_schemer/iterm_schemer/cam02ucs.py", line 7, in <module>
    from colour.utilities import tsplit, tstack
ModuleNotFoundError: No module named 'colour.utilities'; 'colour' is not a package
```

**Comment by crowsonkb** [comment]
Right now `iterm_schemer` depends on my own branch of `colour-science`, which can be installed via `pip3 install git+https://github.com/crowsonkb/colour@JMh`, or else by using the `requirements.txt` in this repository to install all dependencies: `pip3 install -r requirements.txt`.

**Comment by SteveKing** [comment]
Sorry, my mistake. I saw the URL in requirements.txt, but hadn't looked carefully and assumed it was just a reference to the iterm_schemer project.
